name: "Fetch Bing Image"

on:
  push:
    branches:
      - master
    paths:
      - "json/**"
      - "images/**"
  schedule:
    - cron: "0 */2 * * *"
  watch:
    types: [started]

env:
  TZ: Asia/Shanghai

jobs:
  Bing-Spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: "Install dependencies"
        run: python -m pip install --upgrade pip
      - name: "Install requirements"
        run: pip install -r ./requirements.txt
      - name: "Logging"
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` > time.log
      - name: "Working"
        timeout-minutes: 350
        run: bash ./main.sh
      - name: Image Actions
        uses: calibreapp/image-actions@1.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: "80"
          jpegProgressive: false
          pngQuality: "80"
          webpQuality: "80"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Fetch BingImage at $(date +'%Y-%m-%d %H:%M')" -a
      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
